// FontAwesome library configuration
import { library } from '@fortawesome/fontawesome-svg-core';
import {
  faPlay,
  faPause,
  faStop,
  faUpload,
  faDownload,
  faSave,
  faFolderOpen,
  faSliders,
  faMusic,
  faWaveSquare,
  faVolumeHigh,
  faVolumeLow,
  faVolumeOff,
  faPlus,
  faMinus,
  faTrash,
  faCircleInfo,
  faGear,
  faRotateRight,
  faFileAudio,
  faEdit,
  faCheck,
  faTimes,
  faExclamationTriangle,
} from '@fortawesome/free-solid-svg-icons';

// Add icons to the library
library.add(
  faPlay,
  faPause,
  faStop,
  faUpload,
  faDownload,
  faSave,
  faFolderOpen,
  faSliders,
  faMusic,
  faWaveSquare,
  faVolumeHigh,
  faVolumeLow,
  faVolumeOff,
  faPlus,
  faMinus,
  faTrash,
  faCircleInfo,
  faGear,
  faRotateRight,
  faFileAudio,
  faEdit,
  faCheck,
  faTimes,
  faExclamationTriangle,
);
